---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-gateway
  namespace: flux-system
spec:
  chart:
    spec:
      chart: k8s-gateway
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-gateway
  install:
    createNamespace: true
  interval: 1h0m0s
  targetNamespace: k8s-gateway
  values:
    domain: build.couchbase.com
