---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher
  namespace: flux-system
spec:
  chart:
    spec:
      chart: rancher
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: rancher-latest
  install:
    createNamespace: true
  interval: 1h0m0s
  targetNamespace: cattle-system
  values:
    bootstrapPassword: bootstrapPassword
    hostname: rancher.build.couchbase.com
    replicas: 1
    tls: external
