---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  chart:
    spec:
      chart: traefik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: traefik
  install:
    createNamespace: true
  interval: 1h0m0s
  targetNamespace: traefik
  values:
    ingressRoute:
      dashboard:
        enabled: true
    extraObjects:
    - apiVersion: traefik.io/v1alpha1
      kind: TLSStore
      metadata:
        name: default
      spec:
        certificates:
        - secretName: wildcard-build-couchbase-com-secret
