apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-ephemeral
parameters:
  fsType: ext4
  numberOfReplicas: '1'
  staleReplicaTimeout: '2880'
allowVolumeExpansion: true
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
