---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: build-static-pool
  namespace: metallb
spec:
  addresses:
  - 172.23.115.0/24
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: build-static-l2advertisement
  namespace: metallb
spec:
  ipAddressPools:
  - build-static-pool
